FROM python:3.11-slim

WORKDIR /app

COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt

COPY src ./src
COPY data ./data

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.train"]