FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow

EXPOSE 5001

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "/mlflow/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5001", \
     "--allowed-hosts", "mlflow-service,localhost,127.0.0.1", \
     "--cors-allowed-origins", "http://localhost:5001,http://127.0.0.1:5001"]